[package]
name = "stealthdrop"
type = "bin"
authors = [""]
compiler_version = "0.10.3"

[dependencies]
# ecrecover = { tag = "v0.8.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
ecrecover = { tag = "v0.10.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
